coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 0%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
